### ISSUE TITLE
Add DARK FLATS option to frame type

### ISSUE THREAD

**Issue by polakovic** [indigo-astronomy/indigo#387]

**Comment by rumengb** [comment]
I do not think we need it. It will just clutter the property and it is
basically a dark frame for the flat frame. There is no technical difference
between dark frame and dark flat frame. It just have to match the flat
exposure time. So there is no reason to do this.

**Comment by polakovic** [comment]
The reason is, that it is copies to FITS metadata and/or file name. It is repeated user request...

**Comment by polakovic** [comment]
https://pixinsight.com/forum/index.php?threads/understand-darkflat-image-type-in-wbpp-bpp.14545/

**Comment by polakovic** [comment]
825b1d95c91b1225d58b3d72ab8bc6ed155af09d

**Comment by jconejero** [comment]
FWIW, we have had some passionate discussions about the terms 'dark 
flat' and 'flat dark'. See for example:

https://pixinsight.com/forum/index.php?threads/understand-darkflat-image-type-in-wbpp-bpp.14545/#post-88690

https://pixinsight.com/forum/index.php?threads/understand-darkflat-image-type-in-wbpp-bpp.14545/#post-88696

I personally prefer 'flat dark', but our preprocessing pipelines support 
both the FLATDARK and DARKFLAT FITS keywords. I would generate FLATDARK 
keywords because I think it's more correct semantically, but I'm not 
sure about compatibility with other applications.

Juan Conejero
PixInsight Development Team
Pleiades Astrophoto, S.L.
https://pixinsight.com/

**Comment by polakovic** [comment]
Yes, I saw you support both. I googled a little bit and situation is unclear :)

**Comment by jconejero** [comment]
Absolutely unclear, of course. We're speaking of FITS, what did you 
expect? :D
